name: Tests

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup JDK
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Run tests
        run: sbt +test
